#奥运五环

#导入turtle库
import turtle
#导入turtle画笔
turtle.shape('turtle')
#蓝
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.pensize(10)
turtle.pencolor('blue')
turtle.circle(40)
#黑
turtle.penup()
turtle.goto(80,0)
turtle.pendown()
turtle.pensize(10)
turtle.pencolor('black')
turtle.circle(40)
#红
turtle.penup()
turtle.goto(160,0)
turtle.pendown()
turtle.pensize(10)
turtle.pencolor('red')
turtle.circle(40)
#黄
turtle.penup()
turtle.goto(40,-45)
turtle.pendown()
turtle.pensize(10)
turtle.pencolor('yellow')
turtle.circle(40)
#绿
turtle.penup()
turtle.goto(120,-45)
turtle.pendown()
turtle.pensize(10)
turtle.pencolor('green')
turtle.circle(40)
